import Head from 'next/head'
import { Inter, Poppins } from '@next/font/google'
import useMousePosition from '@/js/mousePosHook'
import { useRef } from 'react'

const poppins = Poppins({ subsets: ['latin'], weight: '300' })

export default function Home() {
  const { x, y } = useMousePosition()
  const cursorMediaRef = useRef(null)
  return (
    <>
      <Head>
        <title>Smooth Cursor</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='next'>
        <h1 style={poppins.style} onMouseEnter={() => {
          cursorMediaRef.current.style.transform = `scale(0.5)`
        }}
          onMouseLeave={() => {
            cursorMediaRef.current.style.transform = `scale(0)`
          }}
        >
          Hover Over Me
        </h1>
      </main>
      <div className='cursor' style={{
        transform: `translateX(${x}px) translateY(${y}px)`
      }}>
        <div className='cursorMedia' ref={cursorMediaRef}>
          <video
            src='https://github.com/nthnua/smooth-cursor-demo/raw/main/public/videos/apps.mp4'
            loop
            autoPlay
            muted
            id='apps'
          />
        </div>
      </div>
    </>
  )
}
